### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by Skzter** [Brubi25/Abschlussprojekt-Kniffel#11]
In Menubar gibts "Information" und darin "Rules". Da müsste mal nh Popup kommen mit den ganzen Regeln für das Spiel. 
Hier sind die [Regeln](https://en.wikipedia.org/wiki/Yahtzee).

**Comment by maximmiim** [comment]
Ich hab jetzt mir denn Wikipedia Beitrag zusammengefasst und übersetzt und eingefügt.
