### ISSUE TITLE
Panel + Funktion für Spielende

### ISSUE THREAD

**Issue by Skzter** [Brubi25/Abschlussprojekt-Kniffel#7]
- Funktion die überprüft ob bei jedem Spieler alles ausgefühlt ist und Gesamtpunkte ermittelt und vergleicht
- Panel, welches bei Spielende angezeigt wird mit Auswertung Spiel und Beenden/Neustarten Option

**Comment by maximmiim** [comment]
davincii??

**Comment by Skzter** [comment]
Nix mit Davinci. Hier wird gearbeitet!

**Comment by maximmiim** [comment]
Alles klar Chef!

**Comment by Skzter** [comment]
Text groß mit gewinner name und end game button
b5bec75affde128945db7aabec0bd9f9a43df84e
neustart irrelevant
